# .NET Desktop
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: './Group-Video/OpenVideoCall-Windows/ci.env.py'
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- azure-pipelines

pool:
  vmImage: 'vs2017-win2016'

variables:
  solution: 'Group-Video/OpenVideoCall-Windows/OpenVideoCall.sln'
  buildPlatform: 'Win32'
  buildConfiguration: 'Debug'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
    
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    vsVersion: '12.0'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
